<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('vendor/moment/min/moment-with-langs.min.js')}}"></script>
<script src="{{ asset('vendor/datetimepicker/js/bootstrap-datetimepicker.min.js')}}"></script>
<script src="{{ asset('vendor/chosen/chosen.jquery.min.js') }}"></script>
<script src="{{ asset('vendor/slider/js/bootstrap-slider.js') }}"></script>
<script src="{{ asset('vendor/filestyle/bootstrap-filestyle.min.js') }}"></script>
<script src="{{ asset('vendor/animo/animo.min.js') }}"></script>
<script src="{{ asset('vendor/sparklines/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('vendor/slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('vendor/store/store%2bjson2.min.js') }}"></script>
<script src="{{ asset('vendor/classyloader/js/jquery.classyloader.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.tooltip.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.resize.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.pie.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.time.min.js') }}"></script>
<script src="{{ asset('vendor/flot/jquery.flot.categories.min.js') }}"></script>
<script src="{{ asset('js/admin/app.js') }}"></script>